import type { EditorTool } from "../workspace/tools";
import type { LibraryConstraintKind } from "./editorConstraints";

// Authoring-side body tools all create rigid boundary bodies rather than area-driven physics objects.
export const RIGID_BOUNDARY_LIBRARY_BODY_KINDS = [
  "particle",
  "ball",
  "block",
  "board",
  "polygon",
  "arc-track",
] as const;

export type LibraryBodyKind = (typeof RIGID_BOUNDARY_LIBRARY_BODY_KINDS)[number];
export type LibraryItemKind = LibraryBodyKind | LibraryConstraintKind;
type PhysicalBodyKind = Exclude<LibraryBodyKind, "arc-track" | "particle">;
type RigidBodyPhysicsDefaultKind = Exclude<LibraryBodyKind, "arc-track">;

export type EditorEntityPhysics = {
  mass: number;
  friction: number;
  restitution: number;
  locked: boolean;
  velocityX: number;
  velocityY: number;
};

type BaseEditorSceneEntity = {
  id: string;
  kind: PhysicalBodyKind;
  label: string;
  x: number;
  y: number;
} & EditorEntityPhysics;

export type BallSceneEntity = BaseEditorSceneEntity & {
  kind: "ball";
  radius: number;
};

export type SizedSceneEntity = BaseEditorSceneEntity & {
  kind: "block" | "board" | "polygon";
  width: number;
  height: number;
  rotationDegrees?: number;
};

export type ArcTrackSceneEntity = {
  id: string;
  kind: "arc-track";
  label: string;
  autoGenerated?: boolean;
  anchorEntityId: string;
  anchorEntityKind: "board" | "block";
  anchorEndpoint: "start" | "end";
  center: { x: number; y: number };
  entryEndpoint: "start" | "end";
  side: "inside" | "outside";
  physicsMode: "hybrid-rail-body";
  radius: number;
  sweepAngleDegrees: number;
  rotationDegrees: number;
  // Workspace rendering still consumes the legacy span/thickness fields until Worker A lands
  // the line-guide presentation change.
  centralAngleDegrees: number;
  managedConnection?: {
    sourceEndpoint: "start" | "end";
    sourceEntityId: string;
    targetEndpoint: "start" | "end";
    targetEntityId: string;
  };
  thickness: number;
};

export type EditorSceneEntity = BallSceneEntity | SizedSceneEntity | ArcTrackSceneEntity;

export type EditorState = {
  activeTool: EditorTool;
  gridVisible: boolean;
  selectedConstraintId: string | null;
  selectedEntityId: string | null;
};

const DUPLICATE_OFFSET = 24;
// Classroom rigid bodies use ideal elastic restitution so repeated rebounds stay solver-driven,
// not product-default damping driven.
export const DEFAULT_CLASSROOM_RIGID_BODY_RESTITUTION = 1;
const DEFAULT_ARC_TRACK_SIDE = "inside" as const;
const DEFAULT_ARC_TRACK_PHYSICS_MODE = "hybrid-rail-body" as const;

const DEFAULT_RIGID_BODY_FRICTION_BY_KIND = {
  particle: 0,
  ball: 0,
  block: 0,
  board: 0.42,
  polygon: 0,
} as const;

export function createInitialEditorState(): EditorState {
  return {
    activeTool: "select",
    gridVisible: true,
    selectedConstraintId: null,
    selectedEntityId: null,
  };
}

export function createInitialSceneEntities(): EditorSceneEntity[] {
  return [
    {
      id: "ball-1",
      kind: "ball",
      label: "Ball 1",
      x: 132,
      y: 176,
      radius: 24,
      ...BODY_PHYSICS_DEFAULTS.ball,
    },
    {
      id: "board-1",
      kind: "board",
      label: "Board 1",
      x: 318,
      y: 272,
      width: 120,
      height: 18,
      rotationDegrees: 0,
      ...BODY_PHYSICS_DEFAULTS.board,
    },
  ];
}

const BODY_LABELS: Record<LibraryBodyKind, string> = {
  particle: "Particle",
  ball: "Ball",
  block: "Block",
  board: "Board",
  polygon: "Polygon",
  "arc-track": "Arc Track",
};

const BODY_DEFAULTS = {
  particle: { radius: 4 },
  ball: { radius: 24 },
  block: { width: 84, height: 52 },
  board: { width: 120, height: 14 },
  polygon: { width: 76, height: 76 },
  "arc-track": { radius: 100, sweepAngleDegrees: 90, thickness: 18 },
} as const;

const BODY_PHYSICS_DEFAULTS: Record<RigidBodyPhysicsDefaultKind, EditorEntityPhysics> = {
  particle: {
    mass: 1,
    friction: DEFAULT_RIGID_BODY_FRICTION_BY_KIND.particle,
    restitution: DEFAULT_CLASSROOM_RIGID_BODY_RESTITUTION,
    locked: false,
    velocityX: 0,
    velocityY: 0,
  },
  ball: {
    mass: 1,
    friction: DEFAULT_RIGID_BODY_FRICTION_BY_KIND.ball,
    restitution: DEFAULT_CLASSROOM_RIGID_BODY_RESTITUTION,
    locked: false,
    velocityX: 0,
    velocityY: 0,
  },
  block: {
    mass: 1,
    friction: DEFAULT_RIGID_BODY_FRICTION_BY_KIND.block,
    restitution: DEFAULT_CLASSROOM_RIGID_BODY_RESTITUTION,
    locked: false,
    velocityX: 0,
    velocityY: 0,
  },
  board: {
    mass: 5,
    friction: DEFAULT_RIGID_BODY_FRICTION_BY_KIND.board,
    restitution: DEFAULT_CLASSROOM_RIGID_BODY_RESTITUTION,
    locked: true,
    velocityX: 0,
    velocityY: 0,
  },
  polygon: {
    mass: 2.2,
    friction: DEFAULT_RIGID_BODY_FRICTION_BY_KIND.polygon,
    restitution: DEFAULT_CLASSROOM_RIGID_BODY_RESTITUTION,
    locked: false,
    velocityX: 0,
    velocityY: 0,
  },
};

export function readDefaultRigidBodyFriction(
  kind: RigidBodyPhysicsDefaultKind,
): number {
  return DEFAULT_RIGID_BODY_FRICTION_BY_KIND[kind];
}

export function readDefaultRigidBodyPhysics(
  kind: RigidBodyPhysicsDefaultKind,
): EditorEntityPhysics {
  return {
    ...BODY_PHYSICS_DEFAULTS[kind],
  };
}

export function isLibraryBodyKind(value: string): value is LibraryBodyKind {
  return value in BODY_LABELS;
}

function inferBodyKind(entityId: string): LibraryBodyKind | null {
  const bodyKinds = Object.keys(BODY_LABELS) as LibraryBodyKind[];
  return bodyKinds.find((kind) => entityId.startsWith(`${kind}-`)) ?? null;
}

function getNextEntityIndex(entities: EditorSceneEntity[], kind: LibraryBodyKind): number {
  return entities.filter((entity) => entity.id.startsWith(`${kind}-`)).length + 1;
}

export function createPlacedBodyEntity(
  entities: EditorSceneEntity[],
  kind: LibraryBodyKind,
  position: { x: number; y: number },
): EditorSceneEntity {
  const nextIndex = getNextEntityIndex(entities, kind);
  const id = `${kind}-${nextIndex}`;
  const label = `${BODY_LABELS[kind]} ${nextIndex}`;

  if (kind === "arc-track") {
    return {
      id,
      kind: "arc-track",
      label,
      anchorEntityId: "board-1",
      anchorEntityKind: "board",
      anchorEndpoint: "start",
      center: { x: position.x, y: position.y },
      entryEndpoint: "start",
      side: DEFAULT_ARC_TRACK_SIDE,
      physicsMode: DEFAULT_ARC_TRACK_PHYSICS_MODE,
      radius: BODY_DEFAULTS["arc-track"].radius,
      sweepAngleDegrees: BODY_DEFAULTS["arc-track"].sweepAngleDegrees,
      rotationDegrees: 0,
      centralAngleDegrees: BODY_DEFAULTS["arc-track"].sweepAngleDegrees,
      thickness: BODY_DEFAULTS["arc-track"].thickness,
    };
  }

  const baseEntity = {
    id,
    label,
    x: position.x,
    y: position.y,
    ...BODY_PHYSICS_DEFAULTS[kind],
  };

  switch (kind) {
    case "particle":
      return {
        ...baseEntity,
        kind: "ball",
        radius: BODY_DEFAULTS.particle.radius,
      };
    case "ball":
      return {
        ...baseEntity,
        kind: "ball",
        radius: BODY_DEFAULTS.ball.radius,
      };
    case "block":
      return {
        ...baseEntity,
        kind: "block",
        width: BODY_DEFAULTS.block.width,
        height: BODY_DEFAULTS.block.height,
        rotationDegrees: 0,
      };
    case "board":
      return {
        ...baseEntity,
        kind: "board",
        width: BODY_DEFAULTS.board.width,
        height: BODY_DEFAULTS.board.height,
        rotationDegrees: 0,
      };
    case "polygon":
      return {
        ...baseEntity,
        kind: "polygon",
        width: BODY_DEFAULTS.polygon.width,
        height: BODY_DEFAULTS.polygon.height,
        rotationDegrees: 0,
      };
  }
}

export function createDuplicatedEntity(
  entities: EditorSceneEntity[],
  entity: EditorSceneEntity,
): EditorSceneEntity {
  if (entity.kind === "arc-track") {
    const nextIndex =
      entities.filter((candidate) => candidate.id.startsWith(`${entity.id}-copy-`)).length + 1;

    return {
      ...entity,
      id: `${entity.id}-copy-${nextIndex}`,
      label: `${entity.label} Copy ${nextIndex}`,
      center: {
        x: entity.center.x + DUPLICATE_OFFSET,
        y: entity.center.y + DUPLICATE_OFFSET,
      },
    };
  }

  const duplicatedPosition = {
    x: entity.x + DUPLICATE_OFFSET,
    y: entity.y + DUPLICATE_OFFSET,
  };
  const kind = inferBodyKind(entity.id);

  if (kind) {
    const nextIndex = getNextEntityIndex(entities, kind);
    const baseEntity = {
      ...entity,
      id: `${kind}-${nextIndex}`,
      label: `${BODY_LABELS[kind]} ${nextIndex}`,
      x: duplicatedPosition.x,
      y: duplicatedPosition.y,
    };

    if (entity.kind === "ball") {
      return {
        ...baseEntity,
        kind: "ball",
        radius: entity.radius,
      };
    }

    return {
      ...baseEntity,
      kind: entity.kind,
      width: entity.width,
      height: entity.height,
      rotationDegrees: entity.rotationDegrees ?? 0,
    };
  }

  const nextIndex =
    entities.filter((candidate) => candidate.id.startsWith(`${entity.id}-copy-`)).length + 1;

  if (entity.kind === "ball") {
    return {
      ...entity,
      id: `${entity.id}-copy-${nextIndex}`,
      label: `${entity.label} Copy ${nextIndex}`,
      x: duplicatedPosition.x,
      y: duplicatedPosition.y,
      radius: entity.radius,
    };
  }

  return {
    ...entity,
    id: `${entity.id}-copy-${nextIndex}`,
    label: `${entity.label} Copy ${nextIndex}`,
    x: duplicatedPosition.x,
    y: duplicatedPosition.y,
    width: entity.width,
    height: entity.height,
    rotationDegrees: entity.rotationDegrees ?? 0,
  };
}
