import { describe, expect, it } from "vitest";

import type { EditorSceneEntity } from "./editorStore";
import {
  createManagedSmoothArcPreview,
  reconcileManagedSmoothArcEntities,
  resolveManagedSmoothArcBoardSnap,
} from "./managedSmoothArc";
import { getBoardArcEndpoints } from "./boardArcPlacement";

type BoardEntity = Extract<EditorSceneEntity, { kind: "board" }>;
type ArcTrackEntity = Extract<EditorSceneEntity, { kind: "arc-track" }>;

function createBoard(overrides: Partial<BoardEntity> = {}): BoardEntity {
  return {
    friction: 0,
    height: 0.2,
    id: "board-1",
    kind: "board",
    label: "Board 1",
    locked: true,
    mass: 5,
    restitution: 1,
    rotationDegrees: 0,
    velocityX: 0,
    velocityY: 0,
    width: 2,
    x: 0,
    y: 0,
    ...overrides,
  };
}

function arcContactPoint(
  arc: ArcTrackEntity,
  endpoint: "end" | "start",
): { x: number; y: number } {
  const halfSweep = arc.sweepAngleDegrees / 2;
  const angleDegrees =
    endpoint === "start"
      ? arc.rotationDegrees - halfSweep
      : arc.rotationDegrees + halfSweep;
  const angleRadians = (angleDegrees * Math.PI) / 180;

  return {
    x: arc.center.x + Math.cos(angleRadians) * arc.radius,
    y: arc.center.y - Math.sin(angleRadians) * arc.radius,
  };
}

describe("managedSmoothArc", () => {
  it("creates a deterministic managed smooth arc when two board endpoints are within 0.04 m", () => {
    const boardA = createBoard();
    const boardB = createBoard({
      id: "board-2",
      label: "Board 2",
      rotationDegrees: 30,
      x: 1.846025,
      y: 0.506603,
    });

    const preview = createManagedSmoothArcPreview({
      entities: [boardA, boardB],
      requiredEntityId: "board-2",
    });

    expect(preview).toMatchObject({
      autoGenerated: true,
      anchorEntityId: "board-1",
      anchorEndpoint: "end",
      entryEndpoint: "end",
      id: "smooth-arc-board-1-end-board-2-start",
      kind: "arc-track",
      managedConnection: {
        sourceEndpoint: "end",
        sourceEntityId: "board-1",
        targetEndpoint: "start",
        targetEntityId: "board-2",
      },
      physicsMode: "hybrid-rail-body",
      side: "inside",
    });
    expect(preview?.center.x).toBeCloseTo(1.775358, 6);
    expect(preview?.center.y).toBeCloseTo(0.821051, 6);
    expect(preview?.radius).toBeGreaterThan(0);
    expect(preview?.sweepAngleDegrees).toBeGreaterThan(3);
  });

  it("keeps the inside contact path tangent to the connected board surfaces", () => {
    const boardA = createBoard();
    const boardB = createBoard({
      id: "board-2",
      label: "Board 2",
      rotationDegrees: 30,
      x: 1.846025,
      y: 0.506603,
    });

    const preview = createManagedSmoothArcPreview({
      entities: [boardA, boardB],
      requiredEntityId: "board-2",
    });

    expect(preview).not.toBeNull();

    const sourceContactPoint = arcContactPoint(preview!, "end");

    expect(sourceContactPoint.y).toBeCloseTo(boardA.y, 6);
    expect(sourceContactPoint.x).toBeGreaterThan(boardA.x);
    expect(sourceContactPoint.x).toBeLessThan(boardA.x + boardA.width);
  });

  it("removes an existing managed smooth arc once its endpoints are farther than 0.04 m apart", () => {
    const boardA = createBoard();
    const nearBoardB = createBoard({
      id: "board-2",
      label: "Board 2",
      rotationDegrees: 30,
      x: 1.846025,
      y: 0.506603,
    });
    const withArc = reconcileManagedSmoothArcEntities({
      createMissing: true,
      entities: [boardA, nearBoardB],
      requiredEntityId: "board-2",
    });

    expect(withArc.some((entity) => entity.id === "smooth-arc-board-1-end-board-2-start")).toBe(
      true,
    );

    const farBoardB = {
      ...nearBoardB,
      x: nearBoardB.x + 0.1,
    };
    const reconciled = reconcileManagedSmoothArcEntities({
      entities: withArc.map((entity) => (entity.id === "board-2" ? farBoardB : entity)),
    });

    expect(reconciled.some((entity) => entity.id === "smooth-arc-board-1-end-board-2-start")).toBe(
      false,
    );
  });

  it("snaps a dragged board endpoint exactly onto the matching target board endpoint", () => {
    const boardA = createBoard();
    const boardB = createBoard({
      id: "board-2",
      label: "Board 2",
      rotationDegrees: 30,
      x: 1.846025,
      y: 0.506603,
    });

    const snappedBoard = resolveManagedSmoothArcBoardSnap({
      board: boardB,
      entities: [boardA, boardB],
    });

    expect(snappedBoard).not.toBeNull();

    const boardAEnd = getBoardArcEndpoints(boardA).end.point;
    const boardBStart = getBoardArcEndpoints(snappedBoard!).start.point;

    expect(boardAEnd.x).toBeCloseTo(boardBStart.x, 4);
    expect(boardAEnd.y).toBeCloseTo(boardBStart.y, 4);
  });
});
